---
abstract: 'Shiny formatting for Test::Cukes tests'
author:
  - 'Matthew Lawrence E<lt>mattlaw@cpan.orgE<gt>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TAP-Formatter-Cucumber
provides:
  TAP::Formatter::Cucumber:
    file: lib/TAP/Formatter/Cucumber.pm
    version: 0.01
  TAP::Formatter::Cucumber::Session:
    file: lib/TAP/Formatter/Cucumber/Session.pm
    version: 0
requires:
  Test::Cukes: 0.10
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
